development:
  adapter: postgis
  host: localhost
  encoding: unicode
  pool: 10
  username: postgres
  template: template1
  password: test
  database: development<%= ENV['TEST_ENV_NUMBER'] %>
  port: 5432
  sslmode: disable
test:
  adapter: postgis
  host: localhost
  encoding: unicode
  pool: 10
  username: postgres
  template: template1
  password: test
  database: test<%= ENV['TEST_ENV_NUMBER'] %>
  port: 5432
  sslmode: disable
