development:
  adapter: postgresql
  encoding: utf8
  database: new-airtailor-portal_development
  pool: 5
  username: 
  password:

test: &test
  adapter: postgresql
  encoding: utf8
  database: new-airtailor-portal_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: new-airtailor-portal_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *test
