# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base:  <%= ENV['SECRET_KEY_BASE_DEVELOPMENT'] %>
  shippo_key: <%= ENV['SHIPPO_KEY'] %>
  shippo_api_version: <%= ENV['SHIPPO_API_VERSION'] %>
  shipping_carrier_account: <%= ENV['SHIPPING_CARRIER_ACCOUNT'] %>
  #SONAR_SANDBOX_TOKEN: <%= ENV['SONAR_SANDBOX_TOKEN'] %>
  sonar_sandbox_token: <%= ENV['SONAR_SANDBOX_TOKEN'] %>
  sonar_production_token: <%= ENV['SONAR_PRODUCTION_TOKEN'] %>
  at_gmail_pw: <%= ENV['AT_GMAIL_PW'] %>
  at_gmail_user: <%= ENV['AT_GMAIL_USER'] %>
  delighted_production_token: <%= ENV['DELIGHTED_PRODUCTION_TOKEN'] %>
  postmates_sandbox_token: <%= ENV['POSTMATES_SANDBOX_TOKEN'] %>
  postmates_id: <%= ENV['POSTMATES_ID'] %>
  stripe_api_key: ENV["STRIPE_SECRET_KEY"]

test:
  secret_key_base: <%= ENV['SECRET_KEY_BASE_TEST'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
