development:
  secret_key_base:  <%= ENV['SECRET_KEY_BASE_DEVELOPMENT'] %>
  shippo_key: <%= ENV['SHIPPO_KEY'] %>
  shippo_api_version: <%= ENV['SHIPPO_API_VERSION'] %>
  shipping_carrier_account: <%= ENV['SHIPPING_CARRIER_ACCOUNT'] %>
  sonar_token: <%= ENV['SONAR_SANDBOX_TOKEN'] %>
  at_gmail_pw: <%= ENV['AT_GMAIL_PW'] %>
  at_gmail_user: <%= ENV['AT_GMAIL_USER'] %>
  delighted_token: <%= ENV['DELIGHTED_PRODUCTION_TOKEN'] %>
  postmates_token: <%= ENV['POSTMATES_SANDBOX_TOKEN'] %>
  postmates_id: <%= ENV['POSTMATES_ID'] %>
  shopify_api_key: <%= ENV['SHOPIFY_API_KEY'] %>
  shopify_api_password: <%= ENV['SHOPIFY_API_PASSWORD'] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>

test:
  secret_key_base: <%= ENV['SECRET_KEY_BASE_TEST'] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  postmates_token: <%= ENV['POSTMATES_PRODUCTION_TOKEN'] %>
  sonar_token: <%= ENV['SONAR_PRODUCTION_TOKEN'] %>
  delighted_token: <%= ENV['DELIGHTED_PRODUCTION_TOKEN'] %>
  at_gmail_pw: <%= ENV['AT_GMAIL_PW'] %>
  at_gmail_user: <%= ENV['AT_GMAIL_USER'] %>
  shippo_key: <%= ENV['SHIPPO_KEY'] %>
  shippo_api_version: <%= ENV['SHIPPO_API_VERSION'] %>
  shipping_carrier_account: <%= ENV['SHIPPING_CARRIER_ACCOUNT'] %>
  postmates_id: <%= ENV['POSTMATES_ID'] %>
  postmates_token: <%= ENV['POSTMATES_PRODUCTION_TOKEN'] %>
  shopify_api_key: <%= ENV['SHOPIFY_API_KEY'] %>
  shopify_api_password: <%= ENV['SHOPIFY_API_PASSWORD'] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
